<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="BCrypt.Net-Next" Version="4.1.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.6" />
		<PackageReference Include="Microsoft.IdentityModel.Clients.ActiveDirectory" Version="5.3.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Riaya.Application\Riaya.Application.csproj" />
		<ProjectReference Include="..\Riaya.Domain\Riaya.Domain.csproj" />
		<ProjectReference Include="..\Riaya.Persistence\Riaya.Persistence.csproj" />
	</ItemGroup>

</Project>